### ISSUE TITLE
i can't use this extension

### ISSUE THREAD

**Issue by YSFGH15** [AbrarShakhi/quick-run-in-terminl-deprecated#1]
I've been using this extension for months but a got some issues so it the extension deleted and i tried to search for it but it's gone from market also i download the files from  git hub but still it's not working please can you repost your extension it's 100/100 i need it

**Comment by AbrarShakhi** [comment]
It will be available tomorrow with mor feature and bug fixes.

**Comment by YSFGH15** [comment]
Thank you :)

**Comment by AbrarShakhi** [comment]
Her is the published extention: https://marketplace.visualstudio.com/items?itemName=AbrarShakhi.quick-run-in-terminal
